version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@babel/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@eslint/js"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@quasar/extras"
        update-types: ["version-update:semver-major"]
    groups:
      dependencias-de-produccion:
        dependency-type: production
        update-types:
          - minor
          - patch
      dependencias-de-desarrollo:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
